apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jcasc-pvc 
  namespace: jenkins-ns
spec:
  storageClassName: local-storage
  resources:
    requests:
      storage: "500Mi"
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  
