apiVersion: v1
kind: PersistentVolume
metadata:
  name: jcasc-pv
  labels:
    type: local
spec:
  capacity:
    storage: "500Mi"
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain #pv data will be keeped after removing pvc
  storageClassName: local-storage
  claimRef: # link pv to pvc
    name: jcasc-pvc
    namespace: jenkins-ns
  hostPath:
    path: /c/Users/moaitlahcen/Desktop/kubernetes/JenkinsTp/JCasC
