pipeline{
    podTemplate(containers: [
    containerTemplate(
        name: 'jnlp', 
        image: 'inbound-agent-mine:latest'
        )
  ]) {

    node(POD_LABEL) {
        stage('Get a Maven project') {
            container('jnlp') {
                stage('Shell Execution') {
                    sh '''
                    echo "Hello! I am executing shell"
                    '''
                }
            }
        }

    }
}
}